name: Automation
on:
  pull_request:
    paths: [ "**.tf", "**.md"]
  push:
    branches: [ "main" ]
    paths: [ "**.tf", "**.md"]

permissions: read-all

jobs:
  check-tfdocs:
    if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
    name: Check README with Terraform Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@7a62208a0090636af2df1b739da46d27fd90bdc6 # v1.1.0
        with:
          working-dir: .
          config-file: ".terraform-docs.yml"
          fail-on-diff: true
          output-format: ""
          output-method: ""
          template: ""

  terraform:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.actor != 'dependabot[bot]')
    name: Terraform checks
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Terraform
        run: terraform fmt -check -recursive

  release-please:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: terraform
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee # v4.1.1
        with:
          token: ${{ secrets.MARVIN_PAT }}
          release-type: terraform-module
          config-file: .github/release-please-config.json
