---
name: Status - Code Review

# yamllint disable-line rule:truthy
on:
  pull_request:

permissions: { }
    
jobs:
  build:
    name: Lint code base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@9d8128f17796a16326ceed5a607d5639a47feb82 # v6.4.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_ACTIONS_COMMAND_ARGS: -shellcheck=
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .github/linters
          MARKDOWN_CONFIG_FILE: .markdown-lint.yml
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_MARKDOWN: true
          VALIDATE_TERRAFORM_TFLINT: true
          VALIDATE_YAML: true
  